<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeroPasal.DataAccess\MeroPasal.DataAccess.csproj" />
    <ProjectReference Include="..\MeroPasal.Interface\MeroPasal.Interface.csproj" />
  </ItemGroup>

</Project>
